# **①文章の前処理を行うプログラムを作成**

---

In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
import pandas as pd

# --- 学習データの読み込み ---

In [42]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/imdb_train.csv'
df_train = pd.read_csv(fname, header=None) #学習用データ
df_train

                                                       0  1
0      this film was just brilliant casting location ...  1
1      big hair big boobs bad music and a giant safet...  0
2      this has to be one of the worst films of the 1...  0
3      the scots excel at storytelling the traditiona...  1
4      worst mistake of my life br br i picked this m...  0
...                                                  ... ..
24995  this is a racist movie but worthy of study and...  1
24996  bela lugosi plays a doctor who will do anythin...  0
24997  in a far away galaxy is a planet called ceta i...  0
24998  six degrees had me hooked i looked forward to ...  1
24999  as a big fan of the original film it's hard to...  0

[25000 rows x 2 columns]

In [43]:
X_train_raw, y_train = df_train[0], df_train[1] #学習用データを特徴量とラベルに分ける X_train_rawは何もしてない生のデータの意
X_train_raw, y_train

(0        this film was just brilliant casting location ...
 1        big hair big boobs bad music and a giant safet...
 2        this has to be one of the worst films of the 1...
 3        the scots excel at storytelling the traditiona...
 4        worst mistake of my life br br i picked this m...
                                ...
 24995    this is a racist movie but worthy of study and...
 24996    bela lugosi plays a doctor who will do anythin...
 24997    in a far away galaxy is a planet called ceta i...
 24998    six degrees had me hooked i looked forward to ...
 24999    as a big fan of the original film it's hard to...
 Name: 0, Length: 25000, dtype: object,
 0        1
 1        0
 2        0
 3        1
 4        0
         ..
 24995    1
 24996    0
 24997    0
 24998    1
 24999    0
 Name: 1, Length: 25000, dtype: int64)

# --- Tokenizerの作成・学習 ---

In [44]:
from tensorflow.keras.preprocessing.text import Tokenizer
tok = Tokenizer()
tok.fit_on_texts(X_train_raw) #生のデータを使って学習機の作成

# 単語の確認（必要に応じて）

In [45]:
for i in range(1,21): #ID1からID20の単語
  print(i, tok.index_word[i])

1 the
2 and
3 a
4 of
5 to
6 is
7 br
8 in
9 it
10 i
11 this
12 that
13 was
14 as
15 for
16 with
17 movie
18 but
19 film
20 on

# --- 学習データのテキストを数値化＆パディング ---

In [46]:
X_train_seq = tok.texts_to_sequences(X_train_raw) #単語にIDをつける
X_train_raw[0][:52], X_train_seq[0][:12] #単語とIDの確認

('this film was just brilliant casting location scener',
 [11, 19, 13, 40, 526, 968, 1618, 1381, 62, 455, 4449, 63])

In [47]:
for i in X_train_seq[0][:12]: #IDから元単語に変換できるかどうか
  print(tok.index_word[i])

this
film
was
just
brilliant
casting
location
scenery
story
direction
everyone's
really

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_train_pad = pad_sequences(X_train_seq, maxlen=100) #長さ100にパディング
idx = 0
X_train_pad[idx], len(X_train_pad[idx]) #パディングできてるか確認

(array([ 1408,    30,     3,    19,     9,   212,    25,    74,    49,
            2,    11,   404,    13,    79, 10307,     5,     1,   104,
          114,  5924,    12,   253,     1, 30568,     4,  3734,     2,
          720,    33,    68,    40,   526,   473,    23,   396,   314,
           43,     4,     1, 11926,  1025,    10,   101,    85,     1,
          378,    12,   294,    95,    29,  2064,    53,    23,   138,
            3,   191,  7476,    15,     1,   223,    19,    18,   131,
          473,    23,   477,     2,   141,    27,  5514,    15,    48,
           33,    25,   221,    89,    22,   101,     1,   223,    62,
           13,    35,  1331,    85,     9,    13,   280,     2,    13,
         4450,   110,   100,    29,    12,    13,  5340,    16,   175,
           29], dtype=int32),
 100)

# --- 学習データ保存 ---

In [49]:
X_train_df = pd.DataFrame(X_train_pad)
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_train_X.csv'
X_train_df.to_csv(fname,header=False,index=False)

In [50]:
y_train_df = pd.DataFrame(y_train)
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_train_y.csv'
y_train_df.to_csv(fname, header=False, index=False)

# --- テストデータの読み込み ---

In [51]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/imdb_test.csv'
df_test = pd.read_csv(fname, header=None) #テストデータ
df_test

                                                       0  1
0      please give this one a jack br br interracial ...  0
1      this film comics a lot of compassion because i...  1
2      many animation kicked consider 1200 pineapple ...  1
3      i literally love this type of movie however th...  0
4      like some other people agree i'm a hate hard c...  1
...                                                  ... ..
24995  the book is better than the film mostly becaus...  1
24996  the expressing k to ever see a drops sub in th...  1
24997  i suppose that to say this is an all out terri...  0
24998  in love 2 is the third movie it seemed that it...  0
24999  a good brent boy film is almost required to ha...  0

[25000 rows x 2 columns]

In [52]:
X_test_raw, y_test = df_test[0], df_test[1] #学習用データを特徴量とラベルに分ける X_test_rawは何もしてない生のデータの意
X_test_raw, y_test

(0        please give this one a jack br br interracial ...
 1        this film comics a lot of compassion because i...
 2        many animation kicked consider 1200 pineapple ...
 3        i literally love this type of movie however th...
 4        like some other people agree i'm a hate hard c...
                                ...
 24995    the book is better than the film mostly becaus...
 24996    the expressing k to ever see a drops sub in th...
 24997    i suppose that to say this is an all out terri...
 24998    in love 2 is the third movie it seemed that it...
 24999    a good brent boy film is almost required to ha...
 Name: 0, Length: 25000, dtype: object,
 0        0
 1        1
 2        1
 3        0
 4        1
         ..
 24995    1
 24996    1
 24997    0
 24998    0
 24999    0
 Name: 1, Length: 25000, dtype: int64)

# --- テストデータの数値化＆パディング

In [53]:
X_test_seq = tok.texts_to_sequences(X_test_raw) #単語にIDをつける
X_test_raw[0][:52], X_test_seq[0][:12] #単語とIDの確認

('please give this one a jack br br interracial endeav',
 [588, 199, 11, 28, 3, 714, 7, 7, 18139, 10695, 2, 1])

In [54]:
for i in X_test_seq[0][:12]: #IDから元単語に変換できるかどうか
  print(tok.index_word[i])

please
give
this
one
a
jack
br
br
interracial
endeavor
and
the

In [55]:
X_test_pad = pad_sequences(X_test_seq, maxlen=100) #長さ100にパディング
idx = 0
X_test_pad[idx], len(X_test_pad[idx]) #パディングできてるか確認

(array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,   588,   199,    11,
           28,     3,   714,     7,     7, 18139, 10695,     2,     1,
          357,     4,     1,   174,  5757,   391,   351,     1,   120,
            6,  1032,  1032,  1032,     7,     7,    10,    89,   121,
           86,   485,  7941,    97,    25,  1665,    11,    28,    20,
           24,  7476,    26,   217,   465,     5,   121,    11,   283,
          167,     5,   154,    43,     2,    24,   236,    13,   176,
        15384,    35,    29,    22,  7941,   448,   199,    11,     3,
          714], dtype=int32),
 100)

# --- テストデータ保存 ---

In [56]:
X_test_df = pd.DataFrame(X_test_pad)
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_test_X.csv'
X_test_df.to_csv(fname,header=False,index=False)

In [57]:
y_test_df = pd.DataFrame(y_test)
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_test_y.csv'
y_test_df.to_csv(fname, header=False, index=False)

# --- CSVから読み込み（確認や後続処理用） ---

In [58]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_train_X.csv'
X_train = pd.read_csv(fname,header=None)
X_train

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1408,30,3,19,9,212,25,74,49,2,...,4450,110,100,29,12,13,5340,16,175,29
1,160,8,3210,10086,1,1150,6,191,772,4,...,49,151,459,30,86,75,282,13,142,92
2,1297,1,1866,30,86,75,9,63,13,1,...,103,604,620,32,531,3,224,4,126,110
3,37,17634,10,185,1072,3211,16,1,13421,4,...,23,46,6987,12,562,27,576,18,61,2568
4,10,13,128,2070,246,111,246,226,246,17,...,16,11,2,7180,3,223,248,4,58,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,1,152,5,78,131,501,2,1,2776,558,...,5402,195,645,193,14,22,2536,9,14,1213
24996,10,25,6,1,323,4,32695,7481,135,7481,...,7481,10,479,12,5888,2556,1,356,15,88577
24997,8,3,4074,497,4,14805,86,361,67,26,...,1004,538,9374,4,1,56,10926,1,3561,22540
24998,97,2194,5,1,102,34,66,144,709,72,...,2,21787,9,35,81,77,121,9,6,20
24999,75,1097,14,2340,16226,18,24,9678,6138,2,...,69,4,48,3,1732,19,1,201,128,6

In [59]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_train_y.csv'
y_train = pd.read_csv(fname, header=None)
y_train

       0
0      1
1      0
2      0
3      1
4      0
...   ..
24995  1
24996  0
24997  0
24998  1
24999  0

[25000 rows x 1 columns]

In [60]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_test_X.csv'
X_test = pd.read_csv(fname,header=None)
X_test

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0,0,0,0,0,0,0,0,0,0,...,15384,35,29,22,7941,448,199,11,3,714
1,3,973,2075,4,5290,858,12743,2,4179,27,...,5684,22,200,25,5,815,9,122,1,3074
2,1,5670,4,12,18757,9249,3283,322,9,59,...,8,91,6405,93,18,91,746,6,54,972
3,1,449,8,11,17,6,8651,16,38,473,...,35,92,135,1,606,188,72,25,311,1769
4,780,251,4383,334,2,10,444,11,497,7,...,42,12,49,43774,155,689,30090,155,853,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,3453,21,4279,15,91,2820,4,728,116,2125,...,18,3,690,43,4,155,17,287,316,3560
24996,0,0,0,0,0,0,0,0,0,0,...,1688,4256,8,29,35,22,76,3397,4,203
24997,0,0,0,0,0,0,0,0,0,0,...,27,47,550,359,77,116,9,18,843,5515
24998,0,0,8,116,238,6,1,837,17,9,...,68,533,10,517,11,17,3,2299,4,467
24999,53,93,343,191,305,6,191,18,26,215,...,121,1,28,9,13,90,801,31,2002,2640

In [61]:
fname = '/content/drive/MyDrive/Colab Notebooks/files/parsed_imdb_test_y.csv'
y_test = pd.read_csv(fname,header=None)
y_test

       0
0      0
1      1
2      1
3      0
4      1
...   ..
24995  1
24996  1
24997  0
24998  0
24999  0

[25000 rows x 1 columns]

# --- ラベルのOne-hotエンコーディング ---

In [62]:
from keras.utils import to_categorical
y_train_onehot = to_categorical(y_train)

In [63]:
print("X_train:", X_train.shape)
print("y_train_onehot:", y_train_onehot.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

X_train: (25000, 100)
y_train_onehot: (25000, 2)
X_test: (25000, 100)
y_test: (25000, 1)

## **②通常のニューラルネットワークで機械学習するプログラムを作成**

In [64]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
  Dense(input_dim=100, units=64, activation='relu'),
  Dense(input_dim=64, units=32, activation='relu'),
  Dense(units=2, activation='softmax')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [65]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam'
  )

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         6,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,610 (33.63 KB)

 Trainable params: 8,610 (33.63 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
model.fit(
  X_train, y_train_onehot,
  epochs=30
)

Epoch 1/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 841.3075
Epoch 2/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.0132
Epoch 3/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2.7580
Epoch 4/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 1.9782
Epoch 5/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 1.6307
Epoch 6/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0802
Epoch 7/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.9311
Epoch 8/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.7876
Epoch 9/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7466
Epoch 10/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.7141
Epoch 11/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7037
Epoch 12/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.7018
Epoch 13/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.6933
Epoch 14/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.6937
Epoch 15/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6927
Epoch 16/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.6934
Epoch 17/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6964
Epoch 18/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6929
Epoch 19/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.6929
Epoch 20/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.6931
Epoch 21/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.6929
Epoch 22/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.6931
Epoch 23/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.6930
Epoch 24/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.6930
Epoch 25/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 0.6929
Epoch 26/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.7150
Epoch 27/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.6942
Epoch 28/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.6932
Epoch 29/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.6966
Epoch 30/30
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.6948

In [67]:
import numpy as np

prob = model.predict(X_test)
y_pred = np.argmax(prob,axis=1)
y_pred

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step

array([1, 1, 1, ..., 1, 1, 1])

In [68]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred) #precision, recall
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00     12500
           1       0.50      1.00      0.67     12500

    accuracy                           0.50     25000
   macro avg       0.25      0.50      0.33     25000
weighted avg       0.25      0.50      0.33     25000

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [69]:
from sklearn.metrics import confusion_matrix

c_matrix = confusion_matrix(y_test, y_pred)
print(c_matrix)

[[    0 12500]
 [    0 12500]]

# **③RNNで機械学習するプログラムを作成**

In [70]:
from keras.layers import Embedding, SimpleRNN

dim = X_train.max().max() + 1

model_rnn = Sequential([
  Embedding(dim, 32),
  SimpleRNN(16),
  Dense(2, activation='softmax')
])

In [71]:
model_rnn.compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam'
)

model_rnn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [72]:
model_rnn.fit(
  X_train, y_train_onehot,
  epochs=10
)

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 39s 47ms/step - loss: 0.6433
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 37s 42ms/step - loss: 0.3464
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 42ms/step - loss: 0.1565
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 42ms/step - loss: 0.0609
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 42ms/step - loss: 0.0238
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 42ms/step - loss: 0.0111
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 43s 45ms/step - loss: 0.0514
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 34s 43ms/step - loss: 0.0120
Epoch 9/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 43ms/step - loss: 0.0059
Epoch 10/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 42s 44ms/step - loss: 0.0023

In [73]:
prob = model_rnn.predict(X_test)
y_pred = np.argmax(prob, axis=1)
y_pred

782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step

array([0, 1, 0, ..., 0, 0, 1])

In [74]:
report = classification_report(y_test, y_pred) #precision, recall
print(report)

              precision    recall  f1-score   support

           0       0.72      0.72      0.72     12500
           1       0.72      0.73      0.72     12500

    accuracy                           0.72     25000
   macro avg       0.72      0.72      0.72     25000
weighted avg       0.72      0.72      0.72     25000

In [75]:
c_matrix = confusion_matrix(y_test, y_pred) #混合行列
print(c_matrix)

[[8978 3522]
 [3436 9064]]